//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormClient.ServiceY {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://schemas.datacontract.org/2004/07/ServiceX")]
    [System.SerializableAttribute()]
    public partial class Contract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] citiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commercial_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string country_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] cities {
            get {
                return this.citiesField;
            }
            set {
                if ((object.ReferenceEquals(this.citiesField, value) != true)) {
                    this.citiesField = value;
                    this.RaisePropertyChanged("cities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string commercial_name {
            get {
                return this.commercial_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.commercial_nameField, value) != true)) {
                    this.commercial_nameField = value;
                    this.RaisePropertyChanged("commercial_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string country_code {
            get {
                return this.country_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.country_codeField, value) != true)) {
                    this.country_codeField = value;
                    this.RaisePropertyChanged("country_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VelibStation", Namespace="http://schemas.datacontract.org/2004/07/ServiceX")]
    [System.SerializableAttribute()]
    public partial class VelibStation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int available_bike_standsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int available_bikesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bankingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bike_standsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bonusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contract_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinFormClient.ServiceY.Position positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int available_bike_stands {
            get {
                return this.available_bike_standsField;
            }
            set {
                if ((this.available_bike_standsField.Equals(value) != true)) {
                    this.available_bike_standsField = value;
                    this.RaisePropertyChanged("available_bike_stands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int available_bikes {
            get {
                return this.available_bikesField;
            }
            set {
                if ((this.available_bikesField.Equals(value) != true)) {
                    this.available_bikesField = value;
                    this.RaisePropertyChanged("available_bikes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool banking {
            get {
                return this.bankingField;
            }
            set {
                if ((this.bankingField.Equals(value) != true)) {
                    this.bankingField = value;
                    this.RaisePropertyChanged("banking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bike_stands {
            get {
                return this.bike_standsField;
            }
            set {
                if ((this.bike_standsField.Equals(value) != true)) {
                    this.bike_standsField = value;
                    this.RaisePropertyChanged("bike_stands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bonus {
            get {
                return this.bonusField;
            }
            set {
                if ((this.bonusField.Equals(value) != true)) {
                    this.bonusField = value;
                    this.RaisePropertyChanged("bonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contract_name {
            get {
                return this.contract_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.contract_nameField, value) != true)) {
                    this.contract_nameField = value;
                    this.RaisePropertyChanged("contract_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinFormClient.ServiceY.Position position {
            get {
                return this.positionField;
            }
            set {
                if ((object.ReferenceEquals(this.positionField, value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/ServiceX")]
    [System.SerializableAttribute()]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double lngField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat {
            get {
                return this.latField;
            }
            set {
                if ((this.latField.Equals(value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lng {
            get {
                return this.lngField;
            }
            set {
                if ((this.lngField.Equals(value) != true)) {
                    this.lngField = value;
                    this.RaisePropertyChanged("lng");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceY.IRequestY")]
    public interface IRequestY {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/getContracts", ReplyAction="http://tempuri.org/IRequestY/getContractsResponse")]
        WinFormClient.ServiceY.Contract[] getContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/getContracts", ReplyAction="http://tempuri.org/IRequestY/getContractsResponse")]
        System.Threading.Tasks.Task<WinFormClient.ServiceY.Contract[]> getContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/refreshStationList", ReplyAction="http://tempuri.org/IRequestY/refreshStationListResponse")]
        void refreshStationList(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/refreshStationList", ReplyAction="http://tempuri.org/IRequestY/refreshStationListResponse")]
        System.Threading.Tasks.Task refreshStationListAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/getAllStations", ReplyAction="http://tempuri.org/IRequestY/getAllStationsResponse")]
        WinFormClient.ServiceY.VelibStation[] getAllStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/getAllStations", ReplyAction="http://tempuri.org/IRequestY/getAllStationsResponse")]
        System.Threading.Tasks.Task<WinFormClient.ServiceY.VelibStation[]> getAllStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/GetStation", ReplyAction="http://tempuri.org/IRequestY/GetStationResponse")]
        string GetStation(string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/GetStation", ReplyAction="http://tempuri.org/IRequestY/GetStationResponse")]
        System.Threading.Tasks.Task<string> GetStationAsync(string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/geocodingAddress", ReplyAction="http://tempuri.org/IRequestY/geocodingAddressResponse")]
        WinFormClient.ServiceY.Position geocodingAddress(string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/geocodingAddress", ReplyAction="http://tempuri.org/IRequestY/geocodingAddressResponse")]
        System.Threading.Tasks.Task<WinFormClient.ServiceY.Position> geocodingAddressAsync(string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/computeNearestStation", ReplyAction="http://tempuri.org/IRequestY/computeNearestStationResponse")]
        WinFormClient.ServiceY.VelibStation computeNearestStation(WinFormClient.ServiceY.Position pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/computeNearestStation", ReplyAction="http://tempuri.org/IRequestY/computeNearestStationResponse")]
        System.Threading.Tasks.Task<WinFormClient.ServiceY.VelibStation> computeNearestStationAsync(WinFormClient.ServiceY.Position pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/getURIOfSegment", ReplyAction="http://tempuri.org/IRequestY/getURIOfSegmentResponse")]
        string getURIOfSegment(double dep_lat, double dep_lng, double arr_lat, double arr_lng, string transportation_way);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestY/getURIOfSegment", ReplyAction="http://tempuri.org/IRequestY/getURIOfSegmentResponse")]
        System.Threading.Tasks.Task<string> getURIOfSegmentAsync(double dep_lat, double dep_lng, double arr_lat, double arr_lng, string transportation_way);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequestYChannel : WinFormClient.ServiceY.IRequestY, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestYClient : System.ServiceModel.ClientBase<WinFormClient.ServiceY.IRequestY>, WinFormClient.ServiceY.IRequestY {
        
        public RequestYClient() {
        }
        
        public RequestYClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequestYClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestYClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestYClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinFormClient.ServiceY.Contract[] getContracts() {
            return base.Channel.getContracts();
        }
        
        public System.Threading.Tasks.Task<WinFormClient.ServiceY.Contract[]> getContractsAsync() {
            return base.Channel.getContractsAsync();
        }
        
        public void refreshStationList(string city) {
            base.Channel.refreshStationList(city);
        }
        
        public System.Threading.Tasks.Task refreshStationListAsync(string city) {
            return base.Channel.refreshStationListAsync(city);
        }
        
        public WinFormClient.ServiceY.VelibStation[] getAllStations() {
            return base.Channel.getAllStations();
        }
        
        public System.Threading.Tasks.Task<WinFormClient.ServiceY.VelibStation[]> getAllStationsAsync() {
            return base.Channel.getAllStationsAsync();
        }
        
        public string GetStation(string station) {
            return base.Channel.GetStation(station);
        }
        
        public System.Threading.Tasks.Task<string> GetStationAsync(string station) {
            return base.Channel.GetStationAsync(station);
        }
        
        public WinFormClient.ServiceY.Position geocodingAddress(string location) {
            return base.Channel.geocodingAddress(location);
        }
        
        public System.Threading.Tasks.Task<WinFormClient.ServiceY.Position> geocodingAddressAsync(string location) {
            return base.Channel.geocodingAddressAsync(location);
        }
        
        public WinFormClient.ServiceY.VelibStation computeNearestStation(WinFormClient.ServiceY.Position pos) {
            return base.Channel.computeNearestStation(pos);
        }
        
        public System.Threading.Tasks.Task<WinFormClient.ServiceY.VelibStation> computeNearestStationAsync(WinFormClient.ServiceY.Position pos) {
            return base.Channel.computeNearestStationAsync(pos);
        }
        
        public string getURIOfSegment(double dep_lat, double dep_lng, double arr_lat, double arr_lng, string transportation_way) {
            return base.Channel.getURIOfSegment(dep_lat, dep_lng, arr_lat, arr_lng, transportation_way);
        }
        
        public System.Threading.Tasks.Task<string> getURIOfSegmentAsync(double dep_lat, double dep_lng, double arr_lat, double arr_lng, string transportation_way) {
            return base.Channel.getURIOfSegmentAsync(dep_lat, dep_lng, arr_lat, arr_lng, transportation_way);
        }
    }
}
